version: "3"
services:
  app:
    build:
      context: .
    environment:
      PORT: 3000
      COOKIE_SECRET: "placeholder-secret"
      PGHOST: "db"
      PGUSER: "postgres"
      PGPASSWORD: "supersecretpass"
      PGDATABASE: "postgres"
    ports:
      - "3000:3000"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - "db"
  db:
    image: postgres:14
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: "supersecretpass"
    ports:
      - "5432:5432"
networks:
  internal:
